#!/bin/bash
RESULTS_PATH=/autograder/results/results.json
mkdir -p /autograder/submission/

declare -a SERVICES

python3 /autograder/source/grader/callback_service.py > /dev/null 2>&1 &
if [ $? -ne 0 ]; then
    echo "callback_service won't run."
    exit 1
fi
SERVICES[0]="$!"

cd /autograder/submission/
if [ -f "requirements.txt" ]; then
    pip3 install -r requirements.txt > /dev/null 2>&1
else
    echo "FILE requirements.txt DOES NOT EXIST"
    echo `pwd`
    echo `ls pwd`
fi

cd /autograder/submission/
flask run -p 5000 & #> /dev/null 2>&1 &
if [ $? -ne 0 ]; then
    echo "Could not launch application."
    exit 1
fi
SERVICES[1]="$!"
cd /autograder/source/grader
sleep 3s

python3 /autograder/source/grader/grader_runner.py > $RESULTS_PATH

kill ${SERVICES[0]}
kill ${SERVICES[1]}

cd /autograder/

cat /autograder/results/results.json
